# Numpy exercises


#### 1. Import the numpy package under the name `np` (★☆☆) `hint: import … as`

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆) `hint: vector is a single raw array`

In [3]:
np.random.randint(1,20,10)

array([ 3,  1,  5, 18, 12,  1, 18,  4, 10, 11])

#### 3. How to find the memory size of any array, creat a random 5x6 array and check the sizs (★☆☆)

In [5]:
x=np.random.randint(10,size=(5,6))
x

array([[9, 5, 3, 4, 3, 7],
       [7, 1, 2, 4, 8, 9],
       [4, 8, 3, 5, 7, 3],
       [8, 3, 1, 5, 2, 2],
       [5, 0, 6, 6, 2, 3]])

In [6]:
x.size

30

#### 4. How to get the documentation of the numpy add function from the command line? (★☆☆) `hint: use info or ?`

In [ ]:
print(np.info(np.add))

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆) `hint: array[x]`

In [12]:
x2=np.array([1,1,1,1,1,2,3,4,5,6])
x2

array([1, 1, 1, 1, 1, 2, 3, 4, 5, 6])

#### 7. Create a vector (single raw array) with values ranging from 10 to 49 (★☆☆) `hint: arange`

In [10]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Show how you can Reverse a vector (first element becomes last) (★☆☆)`hint: use index of -1`

In [13]:
x2

array([1, 1, 1, 1, 1, 2, 3, 4, 5, 6])

In [15]:
x2[::-1]

array([6, 5, 4, 3, 2, 1, 1, 1, 1, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) `hint: use range and reshape!`

In [20]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆) `hint: use the np.nonzero`

In [21]:
L=[1,2,0,0,4,0]
np.nonzero(L)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) `hint: use index and use np.eye`
the following is an example of 5x4 identity matrix


```
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

```



SyntaxError: ignored

#### 12. Create a 3x3x3 array with random values (★☆☆) `hint: np.random.random`

In [30]:
x3=np.random.randint(10,size=(3,3,3))
x3

array([[[0, 8, 5],
        [1, 2, 3],
        [6, 6, 2]],

       [[7, 7, 0],
        [4, 9, 7],
        [6, 7, 6]],

       [[6, 8, 3],
        [6, 8, 0],
        [1, 8, 3]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) `hint: min, max`

In [36]:
Z=np.random.randint(100,size=(10,10))
Z

array([[56, 41, 12, 35, 10, 60, 71, 91, 49, 37],
       [81, 15, 64, 20, 59, 38, 30, 35, 41, 41],
       [46, 45, 55, 84, 31,  0, 70, 86, 72, 87],
       [70, 31, 66, 57, 59, 31, 39, 16, 32, 41],
       [55, 29, 11, 48, 63, 69, 31, 61, 41, 62],
       [24, 15, 68, 66, 54, 34, 64, 93, 12, 31],
       [73, 40, 55, 85, 29, 78, 54,  0,  3, 50],
       [87,  9, 68, 94, 96, 37, 76,  3,  2, 62],
       [26, 49, 93, 28, 85, 62, 65, 63, 25, 49],
       [88, 83, 60, 91, 30, 20, 94, 50, 55, 67]])

In [37]:
Z.min()

0

In [38]:
Z.max()

96

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) `hint: mean`

In [39]:
T=np.random.randint(100,size=(30))
T

array([79, 50, 68, 21, 27, 87, 57, 96,  3, 19, 34, 15, 33, 52, 11, 90, 33,
       29, 86, 90, 70, 23, 73, 31, 98,  5, 89, 64, 43, 95])

In [40]:
T.mean()

52.36666666666667

#### 15. Create a 2d array as following, with 1 on the border and 0 inside.. see generated array (★☆☆)



```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```



In [45]:
# Your code
K=np.ones((10,10))
K[1:9,1:9]=0
K

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★★☆) `hint: see generated array np.pad   `

In [46]:
# Your code
J=np.zeros((7,7))
J[1:9,1:9]=1
J

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [47]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

False

 ####18  What is the result of the following expression? (★☆☆) `hint: indexing the nan using np.nan`



```
Z = np.ones((5,5))
Z[0,1]=np.nan
Z
```



In [51]:
Z = np.ones((5,5))
Z[0,1]=np.nan
Z

array([[ 1., nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

#### 18. Now, use this expression to find the index of your nan


```
np.argwhere(x!=x)    Hint: x is your array
```





In [55]:
np.where(Z!=1)

(array([0]), array([1]))

20. Generate the following array 


```
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
```



In [57]:
C=np.arange(1,17).reshape(4,4)
C

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 19. Extract the following values `array([ 1,  6, 11, 16])`. ` Hint: use np.diagonal()`

In [58]:
np.diagonal(C)

array([ 1,  6, 11, 16])

In [ ]:
Z

array([7.29e-44, 1.96e-44, 2.80e-45, 1.35e-43, 5.75e-44, 9.95e-44,
       9.25e-44, 7.85e-44, 6.31e-44, 5.61e-45], dtype=float32)

#### 20. Try to use `np.diag` to Create a 5x5 matrix with diagonal values 11,11,11,11 (★★☆) Hint: use np.diag with k=0 and [11,11,11,11]. -- diag([11,11,11,11],k=-0)

In [68]:
N=np.arange(0,25).reshape(5,5)
np.diag(N,0)=[11]
N



SyntaxError: ignored

#### 21.  Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) `Hint: use k=-1 when calling np.diag`

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


####22. Create a 8x8 matrix and fill it with a given pattern (★☆☆) Hint: use np.zeros and do the replace 



```
[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]
```



In [ ]:
np.random.

[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]


#### 23. Use the `np.tile` to generate the same pattern 

```
[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]
```



In [ ]:
np.tile()

[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]


#### 24. Generate then Normalize a 5x5 random matrix (★☆☆)  `hint: Normalization_array = (x_arr -mean_value(x))/std_value(x)`

#### 25. generate any 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

where 

```
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
```
will return

```
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
```




In [73]:
E= array([ 0, 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
E[3:8]
E

NameError: ignored

In [ ]:
Z = np.arange(11)
# Your code here!. 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 26. Consider an integer vector Z, comment any iligal expressions (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 27. Generate two randon 1D array, How to find common values between two arrays? (★☆☆) `Hint: use intersect1d(Arr1,Arr2)`

In [70]:
np.random.randinat(10,(size=8))

SyntaxError: ignored

#### 28. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
#

####29. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

fauls